
package interfazes;

import Controladores.ClienteControlador;
import java.awt.CardLayout;
import Modelos.Producto;
import Controladores.ProductoControladorEmpleados;
import Controladores.VentasControladorEmpleados;
import Controladores.ClientesControladorEmpleados;
import Modelos.ClienteDao;
import Modelos.ProductoDao;
import Modelos.VentaDao;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Modelos.Venta;
import java.util.ArrayList;


public class interfaz_empleado extends javax.swing.JFrame {
    
    
    Producto p = new Producto();
    ProductoDao pDAO = new ProductoDao();
    DefaultTableModel modelo = new DefaultTableModel();
    private VentasControladorEmpleados ventasControladorEmpleados;
    ClienteDao cDAO = new ClienteDao();
    VentaDao vDAO = new VentaDao();
    ProductoControladorEmpleados productoControladorEmpleados;
    ClientesControladorEmpleados clienteControladorEmpleados;
    

public interfaz_empleado() {
    initComponents();
    setTitle("---La Despensa ---- Gestion Empleado");
    setSize(1150, 750);
    // ==========================================
    // CARD LAYOUT
    // ==========================================

    cardLayout = new CardLayout();
    PanelContenedor.setLayout(cardLayout);

    PanelContenedor.add(PanelInicio, "inicio");
    PanelContenedor.add(PanelProductos, "productos");
    PanelContenedor.add(PanelVentas, "ventas");
    PanelContenedor.add(PanelClientes, "clientes");

    cardLayout.show(PanelContenedor, "inicio");

    // ==========================================
    // CONTROLADOR DE PRODUCTOS
    // ==========================================

    productoControladorEmpleados = new ProductoControladorEmpleados(this, pDAO);

    // ==========================================
    // CONTROLADOR DE CLIENTES
    // ==========================================

    clienteControladorEmpleados = new ClientesControladorEmpleados(
            this,
            cDAO
    );

    // ==========================================
    // CONTROLADOR DE VENTAS
    // ==========================================

    ventasControladorEmpleados = new VentasControladorEmpleados(
            this,
            vDAO,
            pDAO,
            cDAO,

            () -> clienteControladorEmpleados.refrescarTabla(),

            () -> productoControladorEmpleados.refrescarTabla()
    );
    CargarPanelInicioEmpleado(pDAO, vDAO); 
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        PanelContenedor = new javax.swing.JPanel();
        PanelProductos = new javax.swing.JPanel();
        JSPproductos = new javax.swing.JScrollPane();
        tblProductosEmpleados = new javax.swing.JTable();
        lblGestionProductos = new javax.swing.JLabel();
        lblBuscarProductos = new javax.swing.JLabel();
        txtBuscarProductos = new javax.swing.JTextField();
        PanelClientes = new javax.swing.JPanel();
        lblGestion_Clientes = new javax.swing.JLabel();
        lblBuscarClientes = new javax.swing.JLabel();
        txtBuscarClientes = new javax.swing.JTextField();
        JSPClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        PanelDetalleClientes = new javax.swing.JPanel();
        lblDetalleClientes = new javax.swing.JLabel();
        lblIDclientes = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtTelefono_cliente = new javax.swing.JTextField();
        btnAgregarClientes = new javax.swing.JButton();
        btnEditarClientes = new javax.swing.JButton();
        btnEliminarClientes = new javax.swing.JButton();
        PanelInicio = new javax.swing.JPanel();
        pnlTotalVendidoHoy = new java.awt.Panel();
        lblTotalHoyTitulo = new javax.swing.JLabel();
        lblTotalHoyValor = new java.awt.Label();
        pnlVentasHoy = new java.awt.Panel();
        lblVentasHoyTitulo = new javax.swing.JLabel();
        lblVentasHoyValor = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        lblProductosTitulo = new java.awt.Label();
        lblProductosValor = new java.awt.Label();
        lblAlertaTitulo = new javax.swing.JLabel();
        jspStockBajo = new javax.swing.JScrollPane();
        tblStockBajo = new javax.swing.JTable();
        lblTituloGeneral = new javax.swing.JLabel();
        PanelVentas = new javax.swing.JPanel();
        jpTablas = new javax.swing.JPanel();
        lblLVentasListaVentas = new java.awt.Label();
        jspVentas = new javax.swing.JScrollPane();
        tblVentasListVentas = new javax.swing.JTable();
        lblVentasDetalleVenta = new javax.swing.JLabel();
        jspDetalleVentas = new javax.swing.JScrollPane();
        tblVentasDetalleVentaSeleccionada = new javax.swing.JTable();
        lblTotalValor = new java.awt.Label();
        btnAñadirProducto = new javax.swing.JPanel();
        lblVentasRegistrodeventa = new java.awt.Label();
        lblVentasCliente = new java.awt.Label();
        cboVentasCliente = new javax.swing.JComboBox<>();
        txtVentasSeleccionarCantidad = new javax.swing.JTextField();
        jspProductos = new javax.swing.JScrollPane();
        tblVentasRegistroDetalleVenta = new javax.swing.JTable();
        lblVentasTotal = new java.awt.Label();
        cboVentasSeleccionarProducto = new javax.swing.JComboBox<>();
        btnVentasAgregarProducto = new javax.swing.JButton();
        jsptotal = new javax.swing.JScrollPane();
        txtVentasResultadoTotal = new javax.swing.JTextPane();
        lblVentasProducto = new java.awt.Label();
        lblVentasCantidad = new java.awt.Label();
        lblVentasRegistroDetalleVenta = new java.awt.Label();
        btnVentasRestablecer = new javax.swing.JButton();
        btnVentasGuardar = new javax.swing.JButton();
        btnVentasEliminar = new javax.swing.JButton();
        btnVentasActualizar = new javax.swing.JButton();
        lblVentasGestionVentas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenu();
        mnuProductos = new javax.swing.JMenu();
        mnuVentas = new javax.swing.JMenu();
        mnuCerrarSesion = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelContenedor.setBackground(new java.awt.Color(204, 255, 255));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        PanelProductos.setBackground(new java.awt.Color(255, 255, 255));
        PanelProductos.setPreferredSize(new java.awt.Dimension(974, 430));

        tblProductosEmpleados.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        tblProductosEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre ", "Precio", "Stock", "Categoria", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        tblProductosEmpleados.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblProductosEmpleados.setGridColor(new java.awt.Color(224, 224, 224));
        tblProductosEmpleados.setRowHeight(30);
        tblProductosEmpleados.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblProductosEmpleados.setSelectionForeground(new java.awt.Color(33, 33, 33));
        tblProductosEmpleados.setShowGrid(true);
        tblProductosEmpleados.setShowHorizontalLines(true);
        tblProductosEmpleados.setShowVerticalLines(false);
        JSPproductos.setViewportView(tblProductosEmpleados);

        lblGestionProductos.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        lblGestionProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionProductos.setText("Gestion de Productos");

        lblBuscarProductos.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        lblBuscarProductos.setText("Buscar Productos:");

        txtBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestionProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBuscarProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JSPproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblGestionProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarProductos)
                    .addComponent(txtBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSPproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelProductos, "card4");

        lblGestion_Clientes.setBackground(new java.awt.Color(255, 255, 255));
        lblGestion_Clientes.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        lblGestion_Clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestion_Clientes.setText("Gestion de clientes");

        lblBuscarClientes.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblBuscarClientes.setText("Buscar Usuarios");

        tblClientes.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setRowHeight(30);
        tblClientes.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblClientes.setShowGrid(true);
        tblClientes.setShowVerticalLines(false);
        JSPClientes.setViewportView(tblClientes);

        PanelDetalleClientes.setBackground(new java.awt.Color(255, 255, 255));

        lblDetalleClientes.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lblDetalleClientes.setText("Registro Clientes");

        lblIDclientes.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblIDclientes.setText("ID");

        lblNombreCompleto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNombreCompleto.setText("Nombre Completo ");

        lblCorreoElectronico.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblCorreoElectronico.setText("Telefono");

        txtIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDClienteActionPerformed(evt);
            }
        });

        btnAgregarClientes.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregarClientes.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnAgregarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarClientes.setText("Agregar");

        btnEditarClientes.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarClientes.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnEditarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarClientes.setText("Editar");
        btnEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClientesActionPerformed(evt);
            }
        });

        btnEliminarClientes.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarClientes.setText("Eliminar");

        javax.swing.GroupLayout PanelDetalleClientesLayout = new javax.swing.GroupLayout(PanelDetalleClientes);
        PanelDetalleClientes.setLayout(PanelDetalleClientesLayout);
        PanelDetalleClientesLayout.setHorizontalGroup(
            PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleClientesLayout.createSequentialGroup()
                        .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorreoElectronico)
                            .addComponent(lblDetalleClientes)
                            .addComponent(lblNombreCompleto)
                            .addComponent(lblIDclientes))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtTelefono_cliente)
                            .addComponent(txtIDCliente)))
                    .addGroup(PanelDetalleClientesLayout.createSequentialGroup()
                        .addComponent(btnAgregarClientes)
                        .addGap(38, 38, 38)
                        .addComponent(btnEditarClientes)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarClientes)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelDetalleClientesLayout.setVerticalGroup(
            PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetalleClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDclientes)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCompleto)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreoElectronico)
                    .addComponent(txtTelefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarClientes)
                    .addGroup(PanelDetalleClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarClientes)
                        .addComponent(btnEliminarClientes)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelClientesLayout.createSequentialGroup()
                            .addComponent(lblBuscarClientes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblGestion_Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(JSPClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelDetalleClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(756, Short.MAX_VALUE))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblGestion_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarClientes)
                    .addComponent(txtBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSPClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDetalleClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelClientes, "card5");

        PanelInicio.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalHoyTitulo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblTotalHoyTitulo.setText("Total vendido hoy");

        lblTotalHoyValor.setAlignment(java.awt.Label.CENTER);
        lblTotalHoyValor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblTotalHoyValor.setForeground(new java.awt.Color(255, 102, 0));
        lblTotalHoyValor.setText("0");

        javax.swing.GroupLayout pnlTotalVendidoHoyLayout = new javax.swing.GroupLayout(pnlTotalVendidoHoy);
        pnlTotalVendidoHoy.setLayout(pnlTotalVendidoHoyLayout);
        pnlTotalVendidoHoyLayout.setHorizontalGroup(
            pnlTotalVendidoHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalVendidoHoyLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(pnlTotalVendidoHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalHoyValor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalHoyTitulo))
                .addGap(57, 57, 57))
        );
        pnlTotalVendidoHoyLayout.setVerticalGroup(
            pnlTotalVendidoHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalVendidoHoyLayout.createSequentialGroup()
                .addComponent(lblTotalHoyTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalHoyValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblVentasHoyTitulo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblVentasHoyTitulo.setText("Ventas de hoy");

        lblVentasHoyValor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblVentasHoyValor.setForeground(new java.awt.Color(0, 102, 102));
        lblVentasHoyValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasHoyValor.setText("0");

        javax.swing.GroupLayout pnlVentasHoyLayout = new javax.swing.GroupLayout(pnlVentasHoy);
        pnlVentasHoy.setLayout(pnlVentasHoyLayout);
        pnlVentasHoyLayout.setHorizontalGroup(
            pnlVentasHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasHoyLayout.createSequentialGroup()
                .addGroup(pnlVentasHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentasHoyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblVentasHoyTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVentasHoyLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblVentasHoyValor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        pnlVentasHoyLayout.setVerticalGroup(
            pnlVentasHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasHoyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentasHoyTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasHoyValor)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        lblProductosTitulo.setAlignment(java.awt.Label.CENTER);
        lblProductosTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblProductosTitulo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblProductosTitulo.setText("Productos disponibles");

        lblProductosValor.setAlignment(java.awt.Label.CENTER);
        lblProductosValor.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        lblProductosValor.setForeground(new java.awt.Color(0, 102, 0));
        lblProductosValor.setText("0");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblProductosValor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProductosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(lblProductosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductosValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblAlertaTitulo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAlertaTitulo.setText(" 📝 Productos con stock bajo️");

        tblStockBajo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        tblStockBajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto ", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStockBajo.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblStockBajo.setShowHorizontalLines(true);
        jspStockBajo.setViewportView(tblStockBajo);

        lblTituloGeneral.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        lblTituloGeneral.setText("Gestion de Empleados - La Despensa");

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAlertaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelInicioLayout.createSequentialGroup()
                                    .addComponent(pnlVentasHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(pnlTotalVendidoHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jspStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelInicioLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblTituloGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(909, Short.MAX_VALUE))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTituloGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlVentasHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTotalVendidoHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlertaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelInicio, "card6");

        PanelVentas.setBackground(new java.awt.Color(255, 255, 255));
        PanelVentas.setPreferredSize(new java.awt.Dimension(974, 430));

        jpTablas.setBackground(new java.awt.Color(255, 255, 255));

        lblLVentasListaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLVentasListaVentas.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lblLVentasListaVentas.setText("Lista De Ventas");

        tblVentasListVentas.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        tblVentasListVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Cliente", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentasListVentas.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblVentasListVentas.setShowGrid(true);
        tblVentasListVentas.setShowHorizontalLines(true);
        jspVentas.setViewportView(tblVentasListVentas);

        lblVentasDetalleVenta.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lblVentasDetalleVenta.setText("Detalle Venta Seleccionada");

        tblVentasDetalleVentaSeleccionada.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        tblVentasDetalleVentaSeleccionada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Productos", "Cantidad", "P.unitario", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentasDetalleVentaSeleccionada.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblVentasDetalleVentaSeleccionada.setShowGrid(true);
        jspDetalleVentas.setViewportView(tblVentasDetalleVentaSeleccionada);

        javax.swing.GroupLayout jpTablasLayout = new javax.swing.GroupLayout(jpTablas);
        jpTablas.setLayout(jpTablasLayout);
        jpTablasLayout.setHorizontalGroup(
            jpTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablasLayout.createSequentialGroup()
                .addGroup(jpTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jspVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpTablasLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblLVentasListaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablasLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblVentasDetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablasLayout.createSequentialGroup()
                .addComponent(jspDetalleVentas)
                .addContainerGap())
        );
        jpTablasLayout.setVerticalGroup(
            jpTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLVentasListaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasDetalleVenta)
                .addGap(18, 18, 18)
                .addComponent(jspDetalleVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(lblTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAñadirProducto.setBackground(new java.awt.Color(255, 255, 255));

        lblVentasRegistrodeventa.setBackground(new java.awt.Color(255, 255, 255));
        lblVentasRegistrodeventa.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lblVentasRegistrodeventa.setText("Registro De Venta");

        lblVentasCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblVentasCliente.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblVentasCliente.setText("Cliente");

        cboVentasCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboVentasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVentasClienteActionPerformed(evt);
            }
        });

        txtVentasSeleccionarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentasSeleccionarCantidadActionPerformed(evt);
            }
        });

        tblVentasRegistroDetalleVenta.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        tblVentasRegistroDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentasRegistroDetalleVenta.setRowHeight(30);
        tblVentasRegistroDetalleVenta.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblVentasRegistroDetalleVenta.setShowGrid(true);
        tblVentasRegistroDetalleVenta.setShowHorizontalLines(true);
        jspProductos.setViewportView(tblVentasRegistroDetalleVenta);

        lblVentasTotal.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblVentasTotal.setText("Total:");

        cboVentasSeleccionarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboVentasSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVentasSeleccionarProductoActionPerformed(evt);
            }
        });

        btnVentasAgregarProducto.setText("+");

        txtVentasResultadoTotal.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jsptotal.setViewportView(txtVentasResultadoTotal);

        lblVentasProducto.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblVentasProducto.setText("Producto");

        lblVentasCantidad.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblVentasCantidad.setText("Cantidad\n");

        lblVentasRegistroDetalleVenta.setBackground(new java.awt.Color(255, 255, 255));
        lblVentasRegistroDetalleVenta.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lblVentasRegistroDetalleVenta.setText("Registro Detalle Venta");

        btnVentasRestablecer.setBackground(new java.awt.Color(0, 153, 153));
        btnVentasRestablecer.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnVentasRestablecer.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasRestablecer.setText("Restablecer");

        btnVentasGuardar.setBackground(new java.awt.Color(0, 102, 0));
        btnVentasGuardar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnVentasGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasGuardar.setText("Guardar");
        btnVentasGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasGuardarActionPerformed(evt);
            }
        });

        btnVentasEliminar.setBackground(new java.awt.Color(153, 0, 0));
        btnVentasEliminar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnVentasEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasEliminar.setText("Eliminar");
        btnVentasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasEliminarActionPerformed(evt);
            }
        });

        btnVentasActualizar.setBackground(new java.awt.Color(255, 102, 0));
        btnVentasActualizar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnVentasActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasActualizar.setText("Editar");
        btnVentasActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnAñadirProductoLayout = new javax.swing.GroupLayout(btnAñadirProducto);
        btnAñadirProducto.setLayout(btnAñadirProductoLayout);
        btnAñadirProductoLayout.setHorizontalGroup(
            btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblVentasRegistroDetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jspProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblVentasCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboVentasCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                                .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAñadirProductoLayout.createSequentialGroup()
                                        .addComponent(cboVentasSeleccionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                                        .addComponent(lblVentasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(163, 163, 163)))
                                .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVentasCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                                        .addComponent(txtVentasSeleccionarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVentasAgregarProducto))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btnAñadirProductoLayout.createSequentialGroup()
                                .addComponent(lblVentasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsptotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btnAñadirProductoLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblVentasRegistrodeventa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVentasRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentasEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVentasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentasGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAñadirProductoLayout.setVerticalGroup(
            btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentasRegistrodeventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboVentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblVentasRegistroDetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                        .addComponent(lblVentasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboVentasSeleccionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVentasSeleccionarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentasAgregarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jspProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVentasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsptotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblVentasCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVentasRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnAñadirProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVentasGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(btnAñadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentasEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lblVentasGestionVentas.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        lblVentasGestionVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasGestionVentas.setText("Gestion de ventas");

        javax.swing.GroupLayout PanelVentasLayout = new javax.swing.GroupLayout(PanelVentas);
        PanelVentas.setLayout(PanelVentasLayout);
        PanelVentasLayout.setHorizontalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addGroup(PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVentasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVentasGestionVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVentasLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jpTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAñadirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(780, 780, 780))
        );
        PanelVentasLayout.setVerticalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVentasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblVentasGestionVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelVentas, "card5");

        getContentPane().add(PanelContenedor, "card2");

        mnuInicio.setText("inicio");
        mnuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuInicioMouseClicked(evt);
            }
        });
        mnuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicioActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuInicio);

        mnuClientes.setText("Clientes");
        mnuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuClientes);

        mnuProductos.setText("Productos");
        mnuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuProductosMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuProductos);

        mnuVentas.setText("Ventas");
        mnuVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuVentasMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuVentas);

        mnuCerrarSesion.setText("Cerrar sesion");
        mnuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicioActionPerformed

    }//GEN-LAST:event_mnuInicioActionPerformed

    private void txtBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductosActionPerformed

    private void btnEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarClientesActionPerformed

    private void txtIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDClienteActionPerformed

    private void cboVentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVentasClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVentasClienteActionPerformed

    private void txtVentasSeleccionarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentasSeleccionarCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentasSeleccionarCantidadActionPerformed

    private void cboVentasSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVentasSeleccionarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVentasSeleccionarProductoActionPerformed

    private void btnVentasGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasGuardarActionPerformed

    private void btnVentasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasEliminarActionPerformed

    private void btnVentasActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActualizarActionPerformed

    private void mnuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCerrarSesionMouseClicked
        this.dispose();
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);    
    }//GEN-LAST:event_mnuCerrarSesionMouseClicked

    private void mnuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInicioMouseClicked
        CargarPanelInicioEmpleado(pDAO, vDAO);
        cardLayout.show(PanelContenedor, "inicio");        
    }//GEN-LAST:event_mnuInicioMouseClicked

    private void mnuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuClientesMouseClicked
        cardLayout.show(PanelContenedor, "clientes");
    }//GEN-LAST:event_mnuClientesMouseClicked

    private void mnuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProductosMouseClicked
         cardLayout.show(PanelContenedor, "productos");
    }//GEN-LAST:event_mnuProductosMouseClicked

    private void mnuVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuVentasMouseClicked
        ventasControladorEmpleados.actualizarDatosVentas();
        cardLayout.show(PanelContenedor, "ventas");
    }//GEN-LAST:event_mnuVentasMouseClicked

    private void CargarPanelInicioEmpleado(ProductoDao pDAO, VentaDao vDAO) {
    String hoy = java.time.LocalDate.now().toString(); // "yyyy-MM-dd"

    int ventasHoy = 0;
    int totalHoy = 0;
    for (Venta v : vDAO.listarVentas()) {
        if (v.getFecha() != null && v.getFecha().startsWith(hoy)) {
            ventasHoy++;
            totalHoy += v.getTotal();
        }
    }
    lblVentasHoyValor.setText(String.valueOf(ventasHoy));
    lblTotalHoyValor.setText(String.valueOf(totalHoy));

    List<Producto> productos = pDAO.listarTodos();
    lblProductosValor.setText(String.valueOf(productos.size()));

    // Tabla de productos con stock bajo (ajusta el umbral a tu gusto)
    int umbralStockBajo = 5;
    List<Producto> stockBajo = new ArrayList<>();
    for (Producto p : productos) {
        if (p.getStock() <= umbralStockBajo) {
            stockBajo.add(p);
        }
    }
    Object[][] filas = new Object[stockBajo.size()][3];
    for (int i = 0; i < stockBajo.size(); i++) {
        Producto p = stockBajo.get(i);
        filas[i][0] = p.getId_producto();
        filas[i][1] = p.getNombre_producto();
        filas[i][2] = p.getStock();
    }
    String[] columnas = {"ID", "Nombre", "Stock"};
    tblStockBajo.setModel(new javax.swing.table.DefaultTableModel(filas, columnas) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    });
}
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSPClientes;
    private javax.swing.JScrollPane JSPproductos;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelDetalleClientes;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelVentas;
    public javax.swing.JButton btnAgregarClientes;
    private javax.swing.JPanel btnAñadirProducto;
    public javax.swing.JButton btnEditarClientes;
    public javax.swing.JButton btnEliminarClientes;
    public javax.swing.JButton btnVentasActualizar;
    public javax.swing.JButton btnVentasAgregarProducto;
    public javax.swing.JButton btnVentasEliminar;
    public javax.swing.JButton btnVentasGuardar;
    public javax.swing.JButton btnVentasRestablecer;
    public javax.swing.JComboBox<String> cboVentasCliente;
    public javax.swing.JComboBox<String> cboVentasSeleccionarProducto;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpTablas;
    private javax.swing.JScrollPane jspDetalleVentas;
    private javax.swing.JScrollPane jspProductos;
    private javax.swing.JScrollPane jspStockBajo;
    private javax.swing.JScrollPane jspVentas;
    private javax.swing.JScrollPane jsptotal;
    private javax.swing.JLabel lblAlertaTitulo;
    private javax.swing.JLabel lblBuscarClientes;
    private javax.swing.JLabel lblBuscarProductos;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblDetalleClientes;
    private javax.swing.JLabel lblGestionProductos;
    private javax.swing.JLabel lblGestion_Clientes;
    private javax.swing.JLabel lblIDclientes;
    public java.awt.Label lblLVentasListaVentas;
    private javax.swing.JLabel lblNombreCompleto;
    private java.awt.Label lblProductosTitulo;
    private java.awt.Label lblProductosValor;
    private javax.swing.JLabel lblTituloGeneral;
    private javax.swing.JLabel lblTotalHoyTitulo;
    private java.awt.Label lblTotalHoyValor;
    public java.awt.Label lblTotalValor;
    public java.awt.Label lblVentasCantidad;
    public java.awt.Label lblVentasCliente;
    public javax.swing.JLabel lblVentasDetalleVenta;
    private javax.swing.JLabel lblVentasGestionVentas;
    private javax.swing.JLabel lblVentasHoyTitulo;
    private javax.swing.JLabel lblVentasHoyValor;
    public java.awt.Label lblVentasProducto;
    public java.awt.Label lblVentasRegistroDetalleVenta;
    public java.awt.Label lblVentasRegistrodeventa;
    private java.awt.Label lblVentasTotal;
    private javax.swing.JMenu mnuCerrarSesion;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JMenu mnuVentas;
    private java.awt.Panel panel2;
    private java.awt.Panel pnlTotalVendidoHoy;
    private java.awt.Panel pnlVentasHoy;
    public javax.swing.JTable tblClientes;
    public javax.swing.JTable tblProductosEmpleados;
    private javax.swing.JTable tblStockBajo;
    public javax.swing.JTable tblVentasDetalleVentaSeleccionada;
    public javax.swing.JTable tblVentasListVentas;
    public javax.swing.JTable tblVentasRegistroDetalleVenta;
    public javax.swing.JTextField txtBuscarClientes;
    public javax.swing.JTextField txtBuscarProductos;
    public javax.swing.JTextField txtIDCliente;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtTelefono_cliente;
    public javax.swing.JTextPane txtVentasResultadoTotal;
    public javax.swing.JTextField txtVentasSeleccionarCantidad;
    // End of variables declaration//GEN-END:variables
    private CardLayout cardLayout;
}
