package interfazes;


import Controladores.ControladorLogin;
import Controladores.ControladorLogin.ResultadoLogin;
import interfazes.interfaz;
import Modelos.UsuarioRol;

public class Login extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private final ControladorLogin ControladorLogin;
    
    public Login() {
        setTitle("--- La Despensa --- Login");
        initComponents();
        this.ControladorLogin = new ControladorLogin();
    }
    
    private void limpiar_txt(){
        txtUsuario.setText(null);
        jpasswordContraseña.setText(null);
        txtUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginPrincipalBlanco = new javax.swing.JPanel();
        pnlLoginSecundarioAmarillo = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTituloGeneral = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        jpasswordContraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLoginPrincipalBlanco.setBackground(new java.awt.Color(247, 247, 247));

        pnlLoginSecundarioAmarillo.setBackground(new java.awt.Color(255, 255, 255));

        lblBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblBienvenida.setText("¡BIENVENIDO DE NUEVO!");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg.png"))); // NOI18N

        lblTituloGeneral.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        lblTituloGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloGeneral.setText(" La Despensa");

        javax.swing.GroupLayout pnlLoginSecundarioAmarilloLayout = new javax.swing.GroupLayout(pnlLoginSecundarioAmarillo);
        pnlLoginSecundarioAmarillo.setLayout(pnlLoginSecundarioAmarilloLayout);
        pnlLoginSecundarioAmarilloLayout.setHorizontalGroup(
            pnlLoginSecundarioAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginSecundarioAmarilloLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginSecundarioAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginSecundarioAmarilloLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTituloGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginSecundarioAmarilloLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBienvenida)))
                .addGap(14, 14, 14))
        );
        pnlLoginSecundarioAmarilloLayout.setVerticalGroup(
            pnlLoginSecundarioAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginSecundarioAmarilloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenida)
                .addGap(207, 207, 207))
            .addGroup(pnlLoginSecundarioAmarilloLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        btnIniciarSesion.setBackground(new java.awt.Color(247, 247, 247));
        btnIniciarSesion.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario:");

        lblContraseña.setText("Contraseña:");

        btnLogin.setBackground(new java.awt.Color(247, 247, 247));
        btnLogin.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnLogin.setText("------LOGIN ------");
        btnLogin.setBorder(null);

        javax.swing.GroupLayout pnlLoginPrincipalBlancoLayout = new javax.swing.GroupLayout(pnlLoginPrincipalBlanco);
        pnlLoginPrincipalBlanco.setLayout(pnlLoginPrincipalBlancoLayout);
        pnlLoginPrincipalBlancoLayout.setHorizontalGroup(
            pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginPrincipalBlancoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLoginPrincipalBlancoLayout.createSequentialGroup()
                        .addGroup(pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpasswordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addComponent(pnlLoginSecundarioAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginPrincipalBlancoLayout.setVerticalGroup(
            pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginPrincipalBlancoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnLogin)
                .addGap(33, 33, 33)
                .addGroup(pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlLoginPrincipalBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpasswordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlLoginSecundarioAmarillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginPrincipalBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginPrincipalBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
        String Username = txtUsuario.getText();
        String Password = new String(jpasswordContraseña.getPassword());
 
        // Toda la lógica real vive en el Controlador. La Vista solo pregunta y muestra el resultado.
        ResultadoLogin Resultado = ControladorLogin.Autenticar(Username, Password);
 
        if (Resultado.Exitoso) {
            RedirigirSegunRol(Resultado.Usuario.getRol(), Resultado.Usuario);
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    Resultado.Mensaje,
                    "Error de inicio de sesión",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            jpasswordContraseña.setText("");
        }
    }
 
    /**
     * Decide qué ventana abrir según el rol del usuario que acaba de iniciar sesión,
     * y cierra este formulario de Login.
     *
     * TODO: reemplaza "VentanaAdmin" y "VentanaEmpleado" por tus formularios reales
     * (cada uno debería recibir el Usuario autenticado si necesita saber quién entró).
     */
    private void RedirigirSegunRol(UsuarioRol Rol, Modelos.Usuario Usuario) {
        if (Rol == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "El usuario no tiene un rol válido asignado. Contacta al administrador.",
                "Rol no reconocido",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }
 
        switch (Rol) {
            case ADMIN ->{// TODO: new VentanaAdmin(usuario).setVisible(true);
                javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido ADMIN: " + Usuario.getUsername());
                interfaz Iadmin = new interfaz();
                Iadmin.setVisible(true);
                Iadmin.setLocationRelativeTo(null);
            }
            case EMPLEADO -> {// TODO: new VentanaEmpleado(usuario).setVisible(true);
                javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido EMPLEADO: " + Usuario.getUsername());
                interfaz_empleado Iempleado = new interfaz_empleado();
                Iempleado.setVisible(true);
                Iempleado.setLocationRelativeTo(null);
            }
            default -> {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                     "No hay una pantalla configurada para el rol: " + Rol,
                    "Rol sin pantalla asignada",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                        
                );
                return;
            }
        }
        this.dispose(); // cierra el Login una vez que se abrió la ventana correspondiente
    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jpasswordContraseña;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblTituloGeneral;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlLoginPrincipalBlanco;
    private javax.swing.JPanel pnlLoginSecundarioAmarillo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
